---
abstract: 'Terminal frontend to Bot::Cobalt::DB'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Cobalt-DB-Term
provides:
  Bot::Cobalt::DB::Term:
    file: lib/Bot/Cobalt/DB/Term.pm
    version: 0.001
recommends:
  Term::ReadLine::Perl: 0
requires:
  Bot::Cobalt: 0.003
  Carp: 0
  Data::Dumper: 0
  Term::ReadLine: 0
  Term::UI: 0
  Text::ParseWords: 0
  perl: v5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
